### ISSUE TITLE
About error ocurred

### ISSUE THREAD

**Issue by mozgbrasil** [ahmetuysal/nest-hackathon-starter#27]
Good morning my friends

About error ocurred

I'm testing this project and the following error is being returned

    >
     
    node ➜ /workspace/ahmetuysal_nest-hackathon-starter (main ✗) $ ls $(npm bin)
    acorn                        jsesc                       rimraf
    browserslist                 json5                       schematics
    commitlint                   JSONStream                  semver
    conventional-commits-parser  js-yaml                     shjs
    cross-env                    lint-staged                 terser
    cross-env-shell              mime                        tree-kill
    detect-libc                  mkdirp                      tsc
    escodegen                    nanoid                      ts-jest
    esgenerate                   nest                        ts-node
    eslint                       node-pre-gyp                ts-node-cwd
    eslint-config-prettier       node-which                  ts-node-script
    esparse                      nopt                        ts-node-transpile-only
    esvalidate                   opencollective              ts-script
    git-raw-commits              opencollective-postinstall  tsserver
    husky-run                    parser                      uuid
    husky-upgrade                prettier                    webpack
    import-local-fixture         prisma
    jest                         prisma2
     
    >
     
    node ➜ /workspace/ahmetuysal_nest-hackathon-starter (main ✗) $ npm run start:dev
    Debugger attached.

    > nest-hackathon-starter@0.1.0 start:dev /workspace/ahmetuysal_nest-hackathon-starter
    > dotenv -e env/local.env -- nest start --watch

    sh: 1: dotenv: not found
    npm ERR! code ELIFECYCLE
    npm ERR! syscall spawn
    npm ERR! file sh
    npm ERR! errno ENOENT
    npm ERR! nest-hackathon-starter@0.1.0 start:dev: `dotenv -e env/local.env -- nest start --watch`
    npm ERR! spawn ENOENT
    npm ERR! 
    npm ERR! Failed at the nest-hackathon-starter@0.1.0 start:dev script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/node/.npm/_logs/2022-01-18T20_49_32_207Z-debug.log
    Waiting for the debugger to disconnect...

    >

Thanks in advance to everyone who can contribute.

**Comment by ahmetuysal** [comment]
Hi Marcio. It says in the error message that you are missing [`dotenv`](https://www.npmjs.com/package/dotenv) package (which is in project dependencies). Did you install the dependencies? Could you run `npm install` and try again?

**Comment by ahmetuysal** [comment]
Thanks for the detailed explanation @mozgbrasil.

I think we are missing a dependency, I added `dotenv-cli` package to project dependencies. Could you pull the latest commit, run `npm install` and check if you still experience the error?
