### ISSUE TITLE
dialog-zustand.tsx sandbox page does not work out of the box

### ISSUE THREAD

**Issue by chrisLovesCode** [ahmetuysal/nest-hackathon-starter#36]
hey, i just like to let you guys know, that in https://github.com/theodorusclarence/expansion-pack/blob/main/dialog-zustand/src/pages/sandbox/dialog-zustand.tsx
the Layout component as outer wrapper is missing, so i was wondering why no dialog was showing.
maybe <Layout> should be added by default or it should be noted in the install insctructions :)

keep on the good work, love your stack so far!

**Comment by ahmetuysal** [comment]
Hi, I couldn't understand your question. Is there any chance you opened an issue in the wrong repository? Otherwise, could you please elaborate more on your request?

**Comment by chrisLovesCode** [comment]
> Hi, I couldn't understand your question. Is there any chance you opened an issue in the wrong repository? Otherwise, could you please elaborate more on your request?

i'm verry sorry!! i opend in wrong repo.. little confusion between my neXt js and my neSt js codebase :D :D sorry!!
