### ISSUE TITLE
Question - User Entity vs User Model

### ISSUE THREAD

**Issue by twigs67** [ahmetuysal/nest-hackathon-starter#6]
Hello,

I'm looking over your code and I'm wondering why you have UserEntity and UserModel. It looks like duplicate code? What's the purpose of this?

Thanks

**Comment by ahmetuysal** [comment]
Hi, entities are directly related to columns that are stored in the database. Models are objects sent as responses. I wanted to separate these to allow custom arrangements before sending the response to client. This is useful for protecting sensetive fields and simplifying client code. For example, you can discard password from the entity, you can compute the full name from firstName, middleName and lastName and send as a single field.

I am currently traveling and writing this reply from mobile. I will write a more detailed answer with examples soon.

**Comment by ahmetuysal** [comment]
Hi, I updated the project and you see one example from here: [UserResponse](https://github.com/ahmetuysal/nest-hackathon-starter/blob/master/src/user/models/user.response.ts).

**Comment by twigs67** [comment]
Hey @ahmetuysal, thanks for the example!
