### ISSUE TITLE
signup test

### ISSUE THREAD

**Issue by jameskentTX** [ahmetuysal/nest-hackathon-starter#7]
Can you please add signup test to `auth.service.spec` to check if validation of username in `auth.service` `signup` function (or rather in `signup-request.model`) is working as expected?

I changed `@Matches(RegExp(...))` expression and want to test different values of username.

I tried to wite such a test, and tried and tried... With no success unfortunately :)

**Comment by ahmetuysal** [comment]
Hello, end-to-end tests are more suitable for testing request validation logic since request validation middleware runs before request comes to the controller (docs here). I added a sample test in auth.e2e-spec.ts, hope this helps.

**Comment by jameskentTX** [comment]
Thank you very much for explanation and sample test.
