### ISSUE TITLE
There is a warning during `e2e` tests: `A worker process has failed to exit gracefully and has been force exited.`

### ISSUE THREAD

**Issue by jameskentTX** [ahmetuysal/nest-hackathon-starter#8]
To eliminate that warning `afterAll` function from `test/auth.e2e-spec.ts` should be put in `test/app.e2e-spec.ts` file too.
I know it is totally not important :)

**Comment by ahmetuysal** [comment]
Thank you! It would be awesome if you can create a PR.

**Comment by jameskentTX** [comment]
I'm not a professional programmer. I'm not good enough to make PR. Even simplest tasks are difficult for me.
So I'm closing the issue.

**Comment by ahmetuysal** [comment]
Hi @jameskentTX, I am sorry I made you feel that way. I might add changes if you want, but I need you to do this or I will feel bad. It is actually quite simple and you don't need to be a "professional programmer" to do it. You can find some instructions here: https://opensource.com/article/19/7/create-pull-request-github

Thank you for your interest in the project and I will be really happy if you could at least give it a try. I bet we both feel better after you do :)
